{% set name = "schismviz" %}
{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set version = environ.get('VERSION', pyproject.get('tool', {}).get('setuptools_scm', {}).get('fallback_version', '0.0.0')) %}
{% set project = pyproject['project'] %}

package:
  name:           "{{ name|lower }}"
  version:        "{{ version }}"

source:
  path: ..

build:
  script: {{ PYTHON }} -m pip install --no-build-isolation --no-deps --ignore-installed -vv .
  noarch: python
  entry_points:
    {% for script_name, script_ref in project['scripts'].items() %}
    - {{ script_name }} = {{ script_ref }}
    {% endfor %}

requirements:
  build:
    - python
  host:
    - python
    - pip
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() | replace('[toml]', '') }}
    {% endfor %}
  run:
    - python
    {% for dep in project['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}
    # cadwr-dms channel packages (not on PyPI)
    - schimpy
    - dvue
    - vtools
    - dms-datastore

test:
  imports:
    - schismviz
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - numpy
    - xarray
    - shapely
  commands:
    - pytest
    {% for script_name in project['scripts'] %}
    - {{ script_name }} --version
    {% endfor %}

about:
  home: "https://github.com/cadwrdeltamodeling/schismviz"
  summary: "holoviews visualizations for schism"
  license: "MIT"
  license_file: LICENSE

